### ISSUE TITLE
Isabelle Week 0 Review Ticket

### ISSUE THREAD

**Issue by isabelle926** [isabelle926/isabelle_csptri3_individual#1]
# Score: 2.75/3 
### Scrum Team GitHub pages (2 points)
- [x] Web Project: Project Description, Project Plans/Ideas/Wires, Time box
- [x] Team Roles described, Project Owner or Sponsor described, Scrum Board started

### Individual GitHub pages (3 points)
- [x] GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on cspcoders
- [x] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime
- [x] GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime

**Comment by Dylanluo05** [comment]
### Overall Review Score: 2.75/3. ###

### Took off 0.25 points because the Data Structures project was not descriptive enough, and it lacked enough code snippets. ###


#### Individual GitHub pages (3 points) ####

- [X]  GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders (Links to an external site.)](https://cspcoders.nighthawkcodingsociety.com/))

- [X]  GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime

- [X]  GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime
