### ISSUE TITLE
Algorithmic Final

### ISSUE THREAD

**Issue by isabelle926** [isabelle926/isabelle_csptri3_individual#4]
# Score: 9/10
### Grader: Prisha Boreddy
Individual Coding:
- [ ] GitHub Pages showing key learnings and challenges conquered from Tech Talks
- [ ] GitHub commits you have made, show GitHub insights into your code commits.
- [ ] Show Code running on Replit as well as IntelliJ
- [ ] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments
- [ ] List and Loops: show runtime, code organization, code and comments
- [ ] Class review and understanding: show runtime, code organization, code and comments

Crossover stuff
- [ ] Show Crossover contribution:  Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their GitHub repo

Extra
- [ ] Show anything you have done to enhance what you have learned from Python code

https://user-images.githubusercontent.com/70926137/161674129-bb4f4256-d697-4683-bb53-ad080f9b4d58.mp4

**Comment by PrishaB** [comment]
9/10
Everything was included from the code and key learnings demonstrated understanding of Python code. Video was organized and well structured and led the viewer through what they learned successfully. Only thing that is missing is runtime of work added to crossover's code. Otherwise, everything looks very good.
